# This is a basic workflow to help you get started with Actions

name: Build & Deployment

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Release to KDR CR
      - name: Deploy to Container Registry
        run: |
            rm -f NaviLogger/appsettings.json NaviLogger/appsettings.Development.json
            cp -vr NaviLogger/appsettings.Container.json NaviLogger/appsettings.json
            docker login ${{secrets.CONTAINER_REGISTRY}} --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_USERPASSWORD}}
            docker build -t navi_logger:latest -f NaviLogger/Dockerfile .
            docker tag navi_logger:latest ${{secrets.CONTAINER_REGISTRY}}/navi_logger:latest
            docker push ${{secrets.CONTAINER_REGISTRY}}/navi_logger:latest